apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
      - name: temporal
        image: temporalio/auto-setup:latest
        ports:
        - containerPort: 7233
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 7233
  selector:
    app: temporal 